version: "3.7"
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always
  registry-server:
    restart: always
    container_name: registry-server
    image: registry:2
    ports:
      - 5000:5000
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      # REGISTRY_AUTH: htpasswd # uncomment to enable basic authentication
      # REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd # uncomment to enable basic authentication
      # REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm # uncomment to enable basic authentication
    volumes:
      - registry-data:/var/lib/registry
      - ./registry/certs:/certs
      # - ./registry/auth:/auth # uncomment to enable basic authentication
  registry-ui:
    image: joxit/docker-registry-ui:main
    restart: always
    ports:
      - 8010:80
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Docker Registry UI
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=https://registry-server:5000
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=false
      - CATALOG_ELEMENTS_LIMIT=1000
    container_name: registry-ui

volumes:
  portainer_data:
  registry-data:
